name: 'Python CI with pip'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Flask
      run: pip install flask
        
    - name: Copy Python file to EC2 via SSH Key
      uses: appleboy/scp-action@master
      with:
        host: 54.219.93.151
        username: ec2-user
        port: 22
        key: ${{ secrets.KEY }}
        source: "Demo/backend.py"
        target: "~/backend.py"
        
    - name: Run Python file on EC2
      uses: appleboy/ssh-action@master
      with:
        host: 54.219.93.151
        username: ec2-user
        key: ${{ secrets.KEY }} # added key
        port: 22
        script: |
          killall python3
          python3 Demo/backend.py


